spring:
  profiles:
      group:
        dev: dev
        prod: prod
        local: local
---
# ?? ?????? ???? common data.
common: common-data
---
spring.config.activate.on-profile: prod

test:
  a: 10
  b: 20

server:
  address: localhost
  port: 3000
  tomcat:
    threads:
      max: 2
      min-spare: 2
    max-connections: 3

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
---
spring.config.activate.on-profile: dev

test:
  a: 100
  b: 200

server:
  address: localhost
  port: 3001
  tomcat:
    threads:
      max: 2
      min-spare: 2
    max-connections: 3

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update